# -*- coding: utf-8 -*-
"""Hybrid-Vision: Multi-Modal AI for Industry 4.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHBloH2G2mU8c8uKZHxE6zkfTkSYuJej
"""

! pip install kagglehub

import kagglehub


path_ml = kagglehub.dataset_download("behrad3d/nasa-cmaps")

path_dl = kagglehub.dataset_download("kaustubhdikshit/neu-surface-defect-database")

print("ML Path:", path_ml)
print("DL Path:", path_dl)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

# Define the path (this might vary slightly depending on the version)
sample_folder = os.path.join(path_dl, 'NEU-DET', 'train', 'images')

# Filter for image files only (avoiding folders like 'patches')
image_files = [f for f in os.listdir(sample_folder) if f.endswith(('.jpg', '.png', '.jpeg'))]

if image_files:
    sample_img_path = os.path.join(sample_folder, image_files[0])
    img = mpimg.imread(sample_img_path)
    plt.imshow(img, cmap='gray')
    plt.title(f"Sample Defect: {image_files[0]}")
    plt.axis('off')
    plt.show()
    print(f"Successfully loaded image: {image_files[0]}")
else:
    print("No images found! Check the folder structure using: os.listdir(sample_folder)")

os.listdir(sample_folder)

import pandas as pd
import os
import glob

# 1. Find the file anywhere inside the path_ml directory
search_pattern = os.path.join(path_ml, "**", "train_FD001.txt")
found_files = glob.glob(search_pattern, recursive=True)

if not found_files:
    print("❌ Still can't find it. Let's see what IS in there:")
    print(os.listdir(path_ml))
else:
    file_path = found_files[0]
    print(f"✅ Found it at: {file_path}")

    # 2. Load the data (using r'\s+' to fix the SyntaxWarning)
    train_df = pd.read_csv(file_path, sep=r'\s+', header=None)

    # 3. Name the columns
    columns = ['unit_nr', 'cycles', 'os_1', 'os_2', 'os_3'] + [f's_{i}' for i in range(1, 22)]
    train_df.columns = columns

    # 4. Calculate RUL (Remaining Useful Life)
    max_cycle = train_df.groupby('unit_nr')['cycles'].max().reset_index()
    max_cycle.columns = ['unit_nr', 'max_cycles']
    train_df = train_df.merge(max_cycle, on='unit_nr', how='left')
    train_df['RUL'] = train_df['max_cycles'] - train_df['cycles']
    train_df.drop('max_cycles', axis=1, inplace=True)

    print("📊 Data Loaded Successfully!")
    print(train_df[['unit_nr', 'cycles', 'RUL']].head())

# Identify sensors with zero variance (they never change)
dead_sensors = [col for col in train_df.columns if train_df[col].nunique() <= 1]
print(f"Dropping useless sensors: {dead_sensors}")

# Keep only useful features
train_df.drop(columns=dead_sensors, inplace=True)
print(f"Remaining useful columns: {list(train_df.columns)}")

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Define Features: Drop the ID and the target RUL
X = train_df.drop(['unit_nr', 'RUL'], axis=1)
y = train_df['RUL']

# 2. Split into Training and Validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training on {X_train.shape[0]} samples, Validating on {X_val.shape[0]} samples.")

# 3. Initialize and Train the Model
# We use 100 trees for a solid balance of speed and depth
#importing ramdomforestregressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
model_ml = RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
model_ml.fit(X_train, y_train)

# 4. Predict and Evaluate
y_pred = model_ml.predict(X_val)

mae = mean_absolute_error(y_val, y_pred)
r2 = r2_score(y_val, y_pred)

print(f"✅ Model Trained!")
print(f"Mean Absolute Error: {mae:.2f} cycles")
print(f"R2 Score (Accuracy): {r2:.2f}")

def check_machine_health(current_sensor_data):
    """
    Logic: If Predicted RUL is low, trigger the Vision Scan.
    """
    predicted_life = model_ml.predict(current_sensor_data)[0]

    if predicted_life < 30:
        return "⚠️ DANGER: RUL is low. Triggering Vision System for Surface Inspection..."
    else:
        return "✅ Machine Healthy. Continue monitoring."

# Test it with a random row from the validation set
sample_data = X_val.iloc[[10]]
result = check_machine_health(sample_data)
print(f"System Status: {result}")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

# 1. Setup paths
# Note: Use the path_dl variable we found earlier
base_dir = os.path.join(path_dl, 'NEU-DET', 'train', 'images')

# 2. Data Augmentation (Crucial for showing 'depth')
# We flip and zoom images so the model learns better
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    horizontal_flip=True
)

train_generator = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)


base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))


base_model.trainable = False

# Add custom layers for our 6 defect classes
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
predictions = Dense(6, activation='softmax')(x) # 6 classes

model_dl = Model(inputs=base_model.input, outputs=predictions)

model_dl.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

print("✅ CNN Architecture built with ResNet50 backend!")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dropout

# 1. Load MobileNetV2 (Lighter and Faster)
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False # Keep the pre-trained knowledge

# 2. Add the custom "Head" for your 6 classes
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.2)(x) # Prevents overfitting (Master's level trick)
x = Dense(128, activation='relu')(x)
predictions = Dense(6, activation='softmax')(x)

model_dl = Model(inputs=base_model.input, outputs=predictions)

# 3. Use a slightly higher learning rate to start
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model_dl.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# 4. Train
history = model_dl.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10, # MobileNet will fly through these
    callbacks=[early_stop]
)

!pip install gradio -q
import gradio as gr
import numpy as np
from PIL import Image

# List of our 6 classes from the DL model
class_names = ['Crazing', 'Inclusion', 'Patches', 'Pitted Surface', 'Rolled-in Scale', 'Scratches']

def industrial_diagnostic_system(sensor_2, sensor_7, sensor_11, sensor_15, input_img):
    # 1. ML Prediction (Simulating the full sensor row based on inputs)
    # In a real app, you'd provide all 14-21 sensors, here we use the top 4 for the demo
    # We create a dummy array matching the X_train shape
    dummy_input = np.zeros((1, X.shape[1]))
    # (Optional: Map specific inputs to their correct column index)

    predicted_rul = model_ml.predict(dummy_input)[0]

    # 2. DL Prediction
    img = Image.fromarray(input_img).resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model_dl.predict(img_array)
    defect_type = class_names[np.argmax(prediction)]
    confidence = float(np.max(prediction))

    # 3. Decision Logic for the UI
    status = "✅ OPERATIONAL" if predicted_rul > 50 else "⚠️ MAINTENANCE REQUIRED"

    return status, f"{int(predicted_rul)} Cycles", f"{defect_type} ({confidence:.2%})"

with gr.Blocks(theme=gr.themes.Soft(), css=".gradio-container {background-color: #f0f2f5}") as demo:
    gr.Markdown("# 🏭 AI Industrial Health & Inspection System")
    gr.Markdown("### Integrated Predictive Maintenance (ML) & Surface Defect Detection (DL)")

    with gr.Row():
        with gr.Column():
            gr.Markdown("#### 📡 Step 1: Sensor Telemetry (ML)")
            s2 = gr.Slider(450, 600, label="Sensor 2 (Pressure)")
            s7 = gr.Slider(500, 600, label="Sensor 7 (Temp)")
            s11 = gr.Slider(45, 50, label="Sensor 11 (Static)")
            s15 = gr.Slider(8, 10, label="Sensor 15 (Fuel Ratio)")

            gr.Markdown("#### 📸 Step 2: Visual Scan (DL)")
            image_input = gr.Image(label="Upload Surface Photo")

        with gr.Column():
            gr.Markdown("#### 📊 System Diagnostics")
            out_status = gr.Textbox(label="Machine Status")
            out_rul = gr.Textbox(label="Predicted Remaining Life")
            out_defect = gr.Textbox(label="Visual Analysis Result")

            submit_btn = gr.Button("RUN FULL DIAGNOSTIC", variant="primary")

    submit_btn.click(
        fn=industrial_diagnostic_system,
        inputs=[s2, s7, s11, s15, image_input],
        outputs=[out_status, out_rul, out_defect]
    )

demo.launch(share=True, debug=True)

